name: tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_SECRET_KEY: secret-key

    steps:
      - uses: actions/checkout@v2

      - name: Docker - build image
        run: docker build -t msusers .

      - name: Docker - run container
        run: docker run --name msusers -e APP_SECRET_KEY=$APP_SECRET_KEY -d msusers

      - name: Docker - run tests
        run: docker exec msusers coverage run -m pytest

      - name: Docker - coverage
        run: docker exec msusers coverage report

      - name: Docker - stop container
        run: docker stop msusers

      - name: Docker - remove container
        run: docker rm msusers
